check:
  - thoth-build
build:
  base-image: "quay.io/odh-jupyterhub/jupyterhub:3.5.1"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "odh-jupyterhub"
  registry-project: "jupyterhub-img"
  registry-secret: "odh-jupyterhub-thoth-pusher-secret"
